### ISSUE TITLE
Playbox Spotify broke

### ISSUE THREAD

**Issue by cj81499** [Pe8er/Ubersicht-Widgets#4]
Edit: Nevermind, I didn't notice It was removed. However, Spotify fixed applescript not working, so it can be re-added now.

**Comment by cj81499** [comment]
Just saying this again because Spotify fixed applescript (except for Current Progress and Album Art. However, Album Art can still be found with their API)

**Comment by Pe8er** [comment]
Hey man,

I'm sorry to reply this late, for some reason Github is not sending me emails when an issue is opened. Anyway — Playbox is due for overhaul. In the meantime I recommend you check out my [Sidebar](https://github.com/Pe8er/Sidebar.Widget/) - it contains the newest version of Playbox, amongst other goodies.
