### ISSUE TITLE
Widgets won't show up.

### ISSUE THREAD

**Issue by Asweiwu** [Pe8er/Ubersicht-Widgets#6]
I have enabled the widgets.

I was playing a song on iTunes.

But none of the widget showed up.

**Comment by Pe8er** [comment]
Alright, let's take a look. Two requests:

1. Can you please show me the contents of your Ubersicht/Widgets folder?
2. Go to Ubersicht's menubar icon and choose "Show Debug Console".
3. In the Web Inspector window, click on "Console" tab. Let me know if you see anything there.

**Comment by Asweiwu** [comment]
It turned out once I downloaded a lyrics-fetching app for iTunes, it worked.

Thanks for getting back :)
