### ISSUE TITLE
Wallpaper link? 😅

### ISSUE THREAD

**Issue by dubstrike** [Pe8er/Ubersicht-Widgets#7]
Loving the wallpaper you're using in the screenshots. Could you share it, please?

**Comment by Pe8er** [comment]
Sure, here you go https://www.dropbox.com/sh/wlwej72yqrxng3c/AADIdwsacH7zcgl4lWlPTAc7a?dl=0 :)

**Comment by dubstrike** [comment]
Much appreciated!
